In [1]:

import sys, os
sys.path.append(os.path.dirname(os.path.abspath('../')))

import pandas as pd
import numpy as np
from requests import get
from src.scripts.ingestion.data_loader import DataLoader

In [6]:
response = get('https://financialmodelingprep.com/stable/earnings?symbol=AAPL&apikey=27c9e25e9855b9f7194cb65d119b5f47')
df = pd.DataFrame(response.json())

df[df['epsEstimated'].notna()]

,symbol,date,epsActual,epsEstimated,revenueActual,revenueEstimated,lastUpdated
0,AAPL,2026-04-30,NaN,1.9300,NaN,1.091363e+11,2026-04-19
1,AAPL,2026-01-29,2.8500,2.6700,1.437560e+11,1.383910e+11,2026-04-19
2,AAPL,2025-10-30,1.8500,1.7300,1.024660e+11,1.022271e+11,2026-03-26
3,AAPL,2025-07-31,1.5700,1.4400,9.403600e+10,8.956274e+10,2026-03-26
4,AAPL,2025-05-01,1.6500,1.6300,9.535900e+10,9.454218e+10,2026-03-26
...,...,...,...,...,...,...,...
119,AAPL,1996-10-16,-0.0023,-0.0025,2.179000e+09,4.386690e+09,2026-03-26
120,AAPL,1996-04-17,-0.0200,-0.0125,2.185000e+09,1.560714e+09,2026-03-26
121,AAPL,1996-01-17,-0.0050,-0.0025,3.148000e+09,1.574000e+09,2026-03-26
123,AAPL,1995-07-20,0.0075,0.0075,2.575000e+09,2.575000e+09,2026-03-26
124,AAPL,1995-04-20,0.0053,0.0100,2.652000e+09,2.575000e+09,2026-03-26

In [7]:
df.columns

Index(['symbol', 'date', 'epsActual', 'epsEstimated', 'revenueActual',
       'revenueEstimated', 'lastUpdated'],
      dtype='object')

In [ ]:
data_loader = DataLoader()

data_loader.get_data('earnings','AAPL')

{'earnings': {'ticker': 'NVDA',
  'report_period': '2026-01-25',
  'currency': 'USD',
  'quarterly': {'fiscal_period': '2026-Q4',
   'revenue': 68127000000.0,
   'earnings_per_share': 1.76,
   'estimated_earnings_per_share': 1.45,
   'eps_surprise': 'BEAT',
   'net_income': 42960000000.0,
   'gross_profit': 51093000000.0,
   'operating_income': 44299000000.0,
   'weighted_average_shares': 24302000000.0,
   'weighted_average_shares_diluted': 24430000000.0,
   'cash_and_equivalents': 10605000000.0,
   'total_debt': 11040000000.0,
   'total_assets': 206803000000.0,
   'total_liabilities': 49510000000.0,
   'shareholders_equity': 157293000000.0,
   'net_cash_flow_from_operations': None,
   'capital_expenditure': None,
   'net_cash_flow_from_investing': None,
   'net_cash_flow_from_financing': None,
   'change_in_cash_and_equivalents': None,
   'free_cash_flow': 34904000000.0,
   'revenue_chg': 0.1951,
   'net_income_chg': 0.3463,
   'operating_income_chg': 0.2302,
   'gross_profit_chg': 0.2209,
   'free_cash_flow_chg': 0.5783},
  'annual': {'fiscal_period': '2026-FY',
   'revenue': 215938000000.0,
   'earnings_per_share': 4.9,
   'estimated_earnings_per_share': 4.43,
   'eps_surprise': 'BEAT',
   'net_income': 120067000000.0,
   'gross_profit': 153463000000.0,
   'operating_income': 130387000000.0,
   'weighted_average_shares': 24359000000.0,
   'weighted_average_shares_diluted': 24514000000.0,
   'cash_and_equivalents': 10605000000.0,
   'total_debt': 11040000000.0,
   'total_assets': 206803000000.0,
   'total_liabilities': 49510000000.0,
   'shareholders_equity': 157293000000.0,
   'net_cash_flow_from_operations': None,
   'capital_expenditure': None,
   'net_cash_flow_from_investing': None,
   'net_cash_flow_from_financing': None,
   'change_in_cash_and_equivalents': None,
   'free_cash_flow': 96676000000.0,
   'revenue_chg': 0.6547,
   'net_income_chg': 0.6475,
   'operating_income_chg': 0.6008,
   'gross_profit_chg': 0.5682,
   'free_cash_flow_chg': 0.5887}}}

In [7]:
prices = data_loader.get_data('prices','AAPL')

In [15]:
facts = data_loader.get_data('facts','AAPL')

In [5]:
earnings = data_loader.get_data('earnings','AAPL')

## Prices

In [13]:
pd.DataFrame(prices['prices'])

   ticker    open   close    high     low    volume        time
0    AAPL  249.40  248.96  251.83  247.30  34864082  2026-03-19
1    AAPL  247.97  247.99  249.20  246.00  88331081  2026-03-20
2    AAPL  253.97  251.49  254.60  250.28  40546109  2026-03-23
3    AAPL  250.35  251.64  254.82  249.55  45152288  2026-03-24
4    AAPL  254.09  252.62  255.00  251.60  28476668  2026-03-25
5    AAPL  252.12  252.89  257.00  250.77  41796650  2026-03-26
6    AAPL  253.90  248.80  255.49  248.07  47899998  2026-03-27
7    AAPL  250.07  246.63  250.87  245.51  39446213  2026-03-30
8    AAPL  247.91  253.79  255.48  247.10  49598091  2026-03-31
9    AAPL  254.08  255.63  256.18  253.33  40059432  2026-04-01
10   AAPL  254.20  255.92  256.13  250.65  31289369  2026-04-02
11   AAPL  256.51  258.86  262.16  256.46  29329911  2026-04-06
12   AAPL  256.15  253.50  256.20  245.70  62148008  2026-04-07
13   AAPL  258.45  258.90  259.75  256.53  41032772  2026-04-08
14   AAPL  259.00  260.49  261.12  256.07  28121574  2026-04-09
15   AAPL  259.98  260.48  262.19  259.02  31291473  2026-04-10
16   AAPL  259.73  259.20  260.18  256.66  36234698  2026-04-13
17   AAPL  259.25  258.83  261.93  257.19  48370710  2026-04-14
18   AAPL  258.16  266.43  266.56  257.81  49913510  2026-04-15
19   AAPL  266.80  263.40  267.16  261.27  43323112  2026-04-16
20   AAPL  266.96  270.23  272.30  266.72  61436228  2026-04-17

In [32]:
earnings['earnings']

{'ticker': 'AAPL',
 'report_period': '2025-12-27',
 'fiscal_period': '2026-Q1',
 'currency': 'USD',
 'quarterly': {'revenue': 143756000000.0,
  'earnings_per_share': 2.84,
  'estimated_earnings_per_share': 2.65,
  'eps_surprise': 'BEAT',
  'net_income': 42097000000.0,
  'gross_profit': 69231000000.0,
  'operating_income': 50852000000.0,
  'weighted_average_shares': 14748158000.0,
  'weighted_average_shares_diluted': 14810356000.0,
  'cash_and_equivalents': 45317000000.0,
  'total_debt': 90509000000.0,
  'total_assets': 379297000000.0,
  'total_liabilities': 291107000000.0,
  'shareholders_equity': 88190000000.0,
  'net_cash_flow_from_operations': None,
  'capital_expenditure': None,
  'net_cash_flow_from_investing': None,
  'net_cash_flow_from_financing': None,
  'change_in_cash_and_equivalents': None,
  'free_cash_flow': 51552000000.0,
  'revenue_chg': 0.403,
  'net_income_chg': 0.5327,
  'operating_income_chg': 0.5682,
  'gross_profit_chg': 0.4321,
  'free_cash_flow_chg': 0.9464}}

In [11]:
for text in earnings['earnings']['quarterly'].keys():
    print(str(text) + ' TEXT,')

revenue TEXT,
earnings_per_share TEXT,
estimated_earnings_per_share TEXT,
eps_surprise TEXT,
net_income TEXT,
gross_profit TEXT,
operating_income TEXT,
weighted_average_shares TEXT,
weighted_average_shares_diluted TEXT,
cash_and_equivalents TEXT,
total_debt TEXT,
total_assets TEXT,
total_liabilities TEXT,
shareholders_equity TEXT,
net_cash_flow_from_operations TEXT,
capital_expenditure TEXT,
net_cash_flow_from_investing TEXT,
net_cash_flow_from_financing TEXT,
change_in_cash_and_equivalents TEXT,
free_cash_flow TEXT,
revenue_chg TEXT,
net_income_chg TEXT,
operating_income_chg TEXT,
gross_profit_chg TEXT,
free_cash_flow_chg TEXT,

In [19]:
facts['company_facts']

{'ticker': 'AAPL',
 'name': 'Apple Inc',
 'cik': '0000320193',
 'sector': 'Information Technology',
 'industry': 'Technology Hardware, Storage & Peripherals',
 'category': 'Common Stock',
 'exchange': 'NASDAQ',
 'is_active': True,
 'location': 'California; U.S.A',
 'sec_filings_url': 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193',
 'sic_code': '3571.0',
 'sic_industry': 'Electronic Computers',
 'sic_sector': 'Manufacturing'}

In [25]:
pd.DataFrame(prices['prices'])

   ticker    open   close    high     low    volume        time
0    AAPL  249.40  248.96  251.83  247.30  34864082  2026-03-19
1    AAPL  247.97  247.99  249.20  246.00  88331081  2026-03-20
2    AAPL  253.97  251.49  254.60  250.28  40546109  2026-03-23
3    AAPL  250.35  251.64  254.82  249.55  45152288  2026-03-24
4    AAPL  254.09  252.62  255.00  251.60  28476668  2026-03-25
5    AAPL  252.12  252.89  257.00  250.77  41796650  2026-03-26
6    AAPL  253.90  248.80  255.49  248.07  47899998  2026-03-27
7    AAPL  250.07  246.63  250.87  245.51  39446213  2026-03-30
8    AAPL  247.91  253.79  255.48  247.10  49598091  2026-03-31
9    AAPL  254.08  255.63  256.18  253.33  40059432  2026-04-01
10   AAPL  254.20  255.92  256.13  250.65  31289369  2026-04-02
11   AAPL  256.51  258.86  262.16  256.46  29329911  2026-04-06
12   AAPL  256.15  253.50  256.20  245.70  62148008  2026-04-07
13   AAPL  258.45  258.90  259.75  256.53  41032772  2026-04-08
14   AAPL  259.00  260.49  261.12  256.07  28121574  2026-04-09
15   AAPL  259.98  260.48  262.19  259.02  31291473  2026-04-10
16   AAPL  259.73  259.20  260.18  256.66  36234698  2026-04-13
17   AAPL  259.25  258.83  261.93  257.19  48370710  2026-04-14
18   AAPL  258.16  266.43  266.56  257.81  49913510  2026-04-15
19   AAPL  266.80  263.40  267.16  261.27  43323112  2026-04-16
20   AAPL  266.96  270.23  272.30  266.72  61436228  2026-04-17

In [3]:
from utils.dbconnection import DBConnection

db_conn = DBConnection()

db_conn.execute_sql_file('create_raw_schema.sql')

In [4]:
from src.scripts.ingestion.data_loader import DataLoader

data_loader = DataLoader()
data_loader.ingest_raw_data('AAPL')